// Mock applicant data used as a fallback when the API is unavailable.

import type { Applicant } from "./types";

export const MOCK_APPLICANTS: Applicant[] = [
  {
    id: "101",
    firstName: "Juan",
    middleName: "Dela",
    lastName: "Cruz",
    position: "Merchandiser Oncall",
    status: "Training",
    stage: "Initial Interview",
    source: "Walk-In",
    govIds: { sss: true, philhealth: true, pagibig: true, tin: false, umid: false, nationalId: true, passport: false, driverLicense: false, votersCert: false },
    requirements: { nbi: true, medical: true, drugTest: true, xray: true, psaBirthCert: true, diploma: false, signedNda: false, contractSigned: false, resignationCert: false },
    email: "juan.delacruz@example.com",
    phone: "09171234567",
    avatarIndex: 0,
    appliedDate: "2026-08-25",
    interviewDate: "2026-08-29",
    expectedStart: "2026-09-01",
    aiMatchScore: 92,
  },
  {
    id: "102",
    firstName: "Maria",
    middleName: "Santos",
    lastName: "Reyes",
    position: "Store Attendant",
    status: "Probationary",
    stage: "Final Interview",
    source: "Website Portal",
    govIds: { sss: true, philhealth: true, pagibig: true, tin: true, umid: true, nationalId: true, passport: false, driverLicense: false, votersCert: false },
    requirements: { nbi: true, medical: true, drugTest: true, xray: true, psaBirthCert: true, diploma: true, signedNda: true, contractSigned: true, resignationCert: true },
    email: "maria.reyes@example.com",
    phone: "09189876543",
    avatarIndex: 1,
    appliedDate: "2026-08-20",
    interviewDate: "2026-08-30",
    expectedStart: "2026-09-05",
    aiMatchScore: 88,
  },
  {
    id: "103",
    firstName: "Antonio",
    middleName: "Luna",
    lastName: "Garcia",
    position: "Commissary Helper",
    status: "Regular",
    stage: "Job Offer",
    source: "Gmail Submission",
    govIds: { sss: true, philhealth: true, pagibig: false, tin: true, umid: false, nationalId: true, passport: false, driverLicense: true, votersCert: false },
    requirements: { nbi: true, medical: true, drugTest: true, xray: true, psaBirthCert: true, diploma: true, signedNda: false, contractSigned: false, resignationCert: false },
    email: "antonio.garcia@example.com",
    phone: "09205551234",
    avatarIndex: 2,
    appliedDate: "2026-08-18",
    interviewDate: "2026-08-28",
    expectedStart: "2026-09-02",
    aiMatchScore: 95,
  },
  {
    id: "104",
    firstName: "Sofia",
    middleName: "Clara",
    lastName: "Mendoza",
    position: "Intern/Summer Job",
    status: "Training",
    stage: "Initial Interview",
    source: "Summer Job",
    govIds: { sss: false, philhealth: false, pagibig: false, tin: false, umid: false, nationalId: true, passport: false, driverLicense: false, votersCert: false },
    requirements: { nbi: true, medical: false, drugTest: false, xray: false, psaBirthCert: true, diploma: true, signedNda: false, contractSigned: false, resignationCert: false },
    email: "sofia.mendoza@example.com",
    phone: "09224448888",
    avatarIndex: 3,
    appliedDate: "2026-08-26",
    interviewDate: "2026-09-01",
    expectedStart: "2026-09-10",
    aiMatchScore: 81,
  },
  {
    id: "105",
    firstName: "Carlo",
    middleName: "Jose",
    lastName: "Aquino",
    position: "On Call",
    status: "Training",
    stage: "Hired",
    source: "Walk-In",
    govIds: { sss: true, philhealth: true, pagibig: true, tin: true, umid: true, nationalId: true, passport: true, driverLicense: true, votersCert: true },
    requirements: { nbi: true, medical: true, drugTest: true, xray: true, psaBirthCert: true, diploma: true, signedNda: true, contractSigned: true, resignationCert: true },
    email: "carlo.aquino@example.com",
    phone: "09193332211",
    avatarIndex: 4,
    appliedDate: "2026-08-15",
    interviewDate: "2026-08-22",
    expectedStart: "2026-09-01",
    aiMatchScore: 90,
  },
];
