// Mock user accounts used as a fallback when the API is unavailable.

import type { UserReadDto } from "@/lib/services";

export const MOCK_USERS: UserReadDto[] = [
  {
    Id: 1,
    FirstName: "Juan",
    LastName: "Dela Cruz",
    Username: "jdelacruz",
    Email: "juan.delacruz@company.com",
    Role: "Admin",
    Status: "Active",
    Apps: ["hr-management", "recruitment-hiring", "digital-201-file", "attendance-biometrics", "payroll-deduction"],
    Type: "Internal",
    SecurityStamp: "",
    IsActive: true,
  },
  {
    Id: 2,
    FirstName: "Maria",
    LastName: "Santos",
    Username: "msantos",
    Email: "maria.santos@company.com",
    Role: "Manager",
    Status: "Active",
    Apps: ["digital-201-file", "attendance-biometrics", "payroll-deduction"],
    Type: "Internal",
    SecurityStamp: "",
    IsActive: true,
  },
  {
    Id: 3,
    FirstName: "Antonio",
    LastName: "Garcia",
    Username: "agarcia",
    Email: "antonio.garcia@company.com",
    Role: "Employee",
    Status: "Active",
    Apps: ["digital-201-file", "attendance-biometrics"],
    Type: "Internal",
    SecurityStamp: "",
    IsActive: true,
  },
  {
    Id: 4,
    FirstName: "Sofia",
    LastName: "Mendoza",
    Username: "smendoza",
    Email: "sofia.mendoza@company.com",
    Role: "Employee",
    Status: "Inactive",
    Apps: ["attendance-biometrics"],
    Type: "Internal",
    SecurityStamp: "",
    IsActive: false,
  },
  {
    Id: 5,
    FirstName: "Carlo",
    LastName: "Aquino",
    Username: "caquino",
    Email: "carlo.aquino@company.com",
    Role: "Manager",
    Status: "Suspended",
    Apps: ["payroll-deduction", "point-of-sale"],
    Type: "Internal",
    SecurityStamp: "",
    IsActive: false,
  },
  {
    Id: 6,
    FirstName: "Elena",
    LastName: "Reyes",
    Username: "ereyes",
    Email: "elena.reyes@company.com",
    Role: "Employee",
    Status: "Active",
    Apps: ["customer-relation"],
    Type: "External",
    SecurityStamp: "",
    IsActive: true,
  },
];
